authors:
- Thabang Teddy <rttteddy@gmail.com>
description: A Flutter plugin for getting package info.
homepage: <https://pub.dev/packages/package_info_plus>
license: MIT
name: Maverick
repository: <https://github.com/lohanidamodar/package_info_plus>
version: 1.2.0
environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
dependency_overrides: {}